/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotterRouteImport } from './routes/spotter'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as LanguageLearningRouteImport } from './routes/language-learning'
import { Route as IndexRouteImport } from './routes/index'

const SpotterRoute = SpotterRouteImport.update({
  id: '/spotter',
  path: '/spotter',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageLearningRoute = LanguageLearningRouteImport.update({
  id: '/language-learning',
  path: '/language-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/language-learning': typeof LanguageLearningRoute
  '/reading': typeof ReadingRoute
  '/spotter': typeof SpotterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/language-learning': typeof LanguageLearningRoute
  '/reading': typeof ReadingRoute
  '/spotter': typeof SpotterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/language-learning': typeof LanguageLearningRoute
  '/reading': typeof ReadingRoute
  '/spotter': typeof SpotterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/language-learning' | '/reading' | '/spotter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/language-learning' | '/reading' | '/spotter'
  id: '__root__' | '/' | '/language-learning' | '/reading' | '/spotter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LanguageLearningRoute: typeof LanguageLearningRoute
  ReadingRoute: typeof ReadingRoute
  SpotterRoute: typeof SpotterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotter': {
      id: '/spotter'
      path: '/spotter'
      fullPath: '/spotter'
      preLoaderRoute: typeof SpotterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language-learning': {
      id: '/language-learning'
      path: '/language-learning'
      fullPath: '/language-learning'
      preLoaderRoute: typeof LanguageLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LanguageLearningRoute: LanguageLearningRoute,
  ReadingRoute: ReadingRoute,
  SpotterRoute: SpotterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
